import { readFile, writeFile, rename, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { OVERRIDES_FILE, envKey } from '../config';

/**
 * Runtime report overrides — a plain-text, Notepad-editable file (`report-overrides.txt`) layered
 * ON TOP of .env, consulted by the scheduler AT FIRE TIME (never at boot). This is deliberately
 * NOT .env editing:
 *   - .env is regenerated by the platform on every redeploy (UI edits would silently revert);
 *   - .env is only read at boot, so every edit would force a pm2 restart (and a malformed edit
 *     means a crash loop that kills ALL reports).
 * This file instead is re-read fresh on every scheduled run, takes effect from the NEXT run with
 * no restart, and is FAIL-OPEN: if it's missing or a line is malformed, the scheduler ignores it
 * (falling back to .env behavior) and the problem is surfaced in the admin UI — a bad upload can
 * never stop reports.
 *
 * Format (one directive per line, `#` starts a comment):
 *   PAUSE: ALL                                   pause every scheduled report
 *   PAUSE: CPP_575                               pause one section (env-key form)
 *   CPP_575_DAILY_RECIPIENTS: a@x.in, b@y.in     replace that section's daily recipient list
 *   REFINERY_WEEKLY_RECIPIENTS: a@x.in           replace a weekly category's recipient list
 */

export interface OverrideError {
  line: number;
  text: string;
  message: string;
}

export interface Overrides {
  pauseAll: boolean;
  /** Section env-keys (e.g. "CPP_575") whose scheduled reports are paused. */
  pausedKeys: Set<string>;
  /** Full recipient-list replacements, keyed like the env vars: "CPP_575_DAILY_RECIPIENTS". */
  recipients: Map<string, string[]>;
  /** Malformed lines that were skipped (fail-open) — shown in the admin UI. */
  errors: OverrideError[];
}

export function emptyOverrides(): Overrides {
  return { pauseAll: false, pausedKeys: new Set(), recipients: new Map(), errors: [] };
}

const RECIPIENTS_KEY_RE = /^[A-Z0-9_]+_(DAILY|WEEKLY)_RECIPIENTS$/;
// Deliberately loose — corporate addresses vary; we only guard against obvious garbage.
const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

export function parseOverrides(text: string): Overrides {
  const result = emptyOverrides();
  const lines = text.split(/\r?\n/);
  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i];
    const line = raw.replace(/#.*$/, '').trim();
    if (!line) continue;

    const sep = line.indexOf(':');
    if (sep === -1) {
      result.errors.push({ line: i + 1, text: raw.trim(), message: 'Expected "KEY: value" (no ":" found) — line ignored.' });
      continue;
    }
    const key = line.slice(0, sep).trim().toUpperCase();
    const value = line.slice(sep + 1).trim();

    if (key === 'PAUSE') {
      if (!value) {
        result.errors.push({ line: i + 1, text: raw.trim(), message: 'PAUSE needs a value: ALL or a section key like CPP_575 — line ignored.' });
        continue;
      }
      if (value.toUpperCase() === 'ALL') {
        result.pauseAll = true;
      } else {
        result.pausedKeys.add(envKey(value));
      }
      continue;
    }

    if (RECIPIENTS_KEY_RE.test(key)) {
      const emails = value.split(',').map((s) => s.trim()).filter(Boolean);
      const bad = emails.filter((e) => !EMAIL_RE.test(e));
      if (emails.length === 0) {
        result.errors.push({ line: i + 1, text: raw.trim(), message: `${key} has no addresses — line ignored (to pause a section use PAUSE: <KEY> instead).` });
        continue;
      }
      if (bad.length > 0) {
        result.errors.push({ line: i + 1, text: raw.trim(), message: `Not valid email address(es): ${bad.join(', ')} — line ignored.` });
        continue;
      }
      result.recipients.set(key, emails);
      continue;
    }

    result.errors.push({
      line: i + 1,
      text: raw.trim(),
      message: `Unknown directive "${key}" — expected PAUSE or <SECTION>_DAILY_RECIPIENTS / <SECTION>_WEEKLY_RECIPIENTS. Line ignored.`,
    });
  }
  return result;
}

/** The raw file text, or null if the file doesn't exist yet. */
export async function readOverridesText(): Promise<string | null> {
  try {
    return await readFile(OVERRIDES_FILE, 'utf8');
  } catch {
    return null;
  }
}

/**
 * Loads and parses the overrides file. NEVER throws — any read/parse problem returns empty
 * overrides (i.e. exact current .env behavior), because a broken overrides file must never be
 * able to stop or crash a scheduled report.
 */
export async function loadOverrides(): Promise<Overrides> {
  try {
    const text = await readOverridesText();
    if (text === null) return emptyOverrides();
    return parseOverrides(text);
  } catch (err) {
    console.error('[overrides] Could not load report-overrides.txt (ignoring it, using .env values):', err);
    return emptyOverrides();
  }
}

/** Whether this section (unit or weekly category, by display name or key) is paused. */
export function isPaused(ov: Overrides, sectionName: string): boolean {
  return ov.pauseAll || ov.pausedKeys.has(envKey(sectionName));
}

/** The override recipient list for a section, or null to fall back to .env resolution. */
export function overrideRecipients(ov: Overrides, sectionName: string, type: 'daily' | 'weekly'): string[] | null {
  return ov.recipients.get(`${envKey(sectionName)}_${type.toUpperCase()}_RECIPIENTS`) ?? null;
}

const FILE_HEADER = `# HMEL report overrides — edit here or in the admin UI ("Schedule Report" tab).
# Re-read on every scheduled run; changes apply from the NEXT run, no restart needed.
# Malformed lines are IGNORED (reports fall back to .env) and flagged in the admin UI.
#
#   PAUSE: ALL                                  pause every scheduled report
#   PAUSE: CPP_575                              pause one section (env-key form)
#   CPP_575_DAILY_RECIPIENTS: a@x.in, b@y.in    replace that section's daily recipients
#   REFINERY_WEEKLY_RECIPIENTS: a@x.in          replace a weekly category's recipients
#
# NOTE: structured edits from the UI rewrite this file — keep hand-written comments above this line only.
`;

/** Serializes an Overrides model back to canonical file text (used by the UI's structured edits). */
export function serializeOverrides(ov: Overrides): string {
  const lines: string[] = [FILE_HEADER];
  if (ov.pauseAll) lines.push('PAUSE: ALL');
  for (const key of [...ov.pausedKeys].sort()) lines.push(`PAUSE: ${key}`);
  if (ov.pauseAll || ov.pausedKeys.size > 0) lines.push('');
  for (const [key, emails] of [...ov.recipients.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`${key}: ${emails.join(', ')}`);
  }
  return lines.join('\n') + '\n';
}

/**
 * Atomically replaces the overrides file (write temp + rename), so the scheduler can never read a
 * half-written file even if it fires at the same instant.
 */
export async function writeOverridesText(text: string): Promise<void> {
  await mkdir(path.dirname(OVERRIDES_FILE), { recursive: true });
  const tmp = `${OVERRIDES_FILE}.tmp-${process.pid}-${Date.now()}`;
  await writeFile(tmp, text, 'utf8');
  await rename(tmp, OVERRIDES_FILE);
}
